// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DAL.Data;

#nullable disable

namespace MovieApp.DAL.Data.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    partial class MovieAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.DAL.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Hollywood Blvd,Los Angeles,CA",
                            Age = 74,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his work in blockbuster films",
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "200 Sunset Blvd, Los Angeles, CA",
                            Age = 53,
                            City = "Los Angeles",
                            Description = "A British-American film director known for complex storytelling",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Address = "300 Vine St, Hollywood, CA",
                            Age = 60,
                            City = "Hollywood",
                            Description = "An American filmmaker famous for non-linear narratives",
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Address = "400 Broadway, New York, NY",
                            Age = 81,
                            City = "New York",
                            Description = "An American director known for crime and drama films",
                            Name = "Martin Scorsese"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
