// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DAL.Data;

#nullable disable

namespace MovieApp.DAL.Data.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    partial class MovieAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.DAL.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Hollywood Blvd,Los Angeles,CA",
                            Age = 74,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his work in blockbuster films",
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "200 Sunset Blvd, Los Angeles, CA",
                            Age = 53,
                            City = "Los Angeles",
                            Description = "A British-American film director known for complex storytelling",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Address = "300 Vine St, Hollywood, CA",
                            Age = 60,
                            City = "Hollywood",
                            Description = "An American filmmaker famous for non-linear narratives",
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Address = "400 Broadway, New York, NY",
                            Age = 81,
                            City = "New York",
                            Description = "An American director known for crime and drama films",
                            Name = "Martin Scorsese"
                        });
                });

            modelBuilder.Entity("MovieApp.DAL.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Imdb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A thief who steals secrets through dreams is given a final mission.",
                            DirectorId = 1,
                            Duration = 148,
                            Imdb = 8.8m,
                            ReleaseYear = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Batman faces the Joker, a criminal mastermind who spreads chaos.",
                            DirectorId = 1,
                            Duration = 152,
                            Imdb = 9.0m,
                            ReleaseYear = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A group of astronauts travel through a wormhole to save humanity.",
                            DirectorId = 2,
                            Duration = 169,
                            Imdb = 8.6m,
                            ReleaseYear = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Two prisoners form a deep friendship over many years.",
                            DirectorId = 2,
                            Duration = 142,
                            Imdb = 9.3m,
                            ReleaseYear = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The life story of a simple man with a big heart.",
                            DirectorId = 3,
                            Duration = 142,
                            Imdb = 8.8m,
                            ReleaseYear = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A hacker discovers the true nature of his reality and fights against its controllers.",
                            DirectorId = 4,
                            Duration = 136,
                            Imdb = 8.7m,
                            ReleaseYear = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        });
                });

            modelBuilder.Entity("MovieApp.DAL.Models.Movie", b =>
                {
                    b.HasOne("MovieApp.DAL.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MovieApp.DAL.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
